version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      dotnet: 3.1
  pre_build:
    on-failure: ABORT
    commands:
    - echo Build start on 'date'
    - echo Build ends on 'date'
  build:
    on-failure: ABORT
    commands:
    - echo Build start on 'date'
    - dotnet build
    - dotnet test
    - echo Build ends on 'date'
